// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZBczR4oKUf8r-Rqoyl3p8Y-d8q3vqY3w',
    appId: '1:107720447480:web:5a7d6b9dc10bbde258f20d',
    messagingSenderId: '107720447480',
    projectId: 'palease',
    authDomain: 'palease.firebaseapp.com',
    storageBucket: 'palease.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCodwGR6bFCVwO4OSTCAPmtDMP4E0JT-uk',
    appId: '1:107720447480:android:2a90fab17977970558f20d',
    messagingSenderId: '107720447480',
    projectId: 'palease',
    storageBucket: 'palease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDFibxxIY04pZXgZwHOtM5vXrs4e0mKDw',
    appId: '1:107720447480:ios:2d2f840edb3db1a358f20d',
    messagingSenderId: '107720447480',
    projectId: 'palease',
    storageBucket: 'palease.appspot.com',
    iosBundleId: 'com.example.graduationproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDFibxxIY04pZXgZwHOtM5vXrs4e0mKDw',
    appId: '1:107720447480:ios:cb61d179ecc2f73458f20d',
    messagingSenderId: '107720447480',
    projectId: 'palease',
    storageBucket: 'palease.appspot.com',
    iosBundleId: 'com.example.graduationproject.RunnerTests',
  );
}
